# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17XAP2gbu8hxWGhIeCdwAg6WrI59ndzJs
"""

# The file object attributes

# 1.	fo = open("foo.txt", "wb") 
# 2.	print ("Name of the file: ", fo.name) 
# 3.	print ("Closed or not : ", fo.closed) 
# 4.	print ("Opening mode : ", fo.mode) 
# 5.	fo.close()

# The write() method

# 1.	file = open("test.txt", "w") 
# 2.	file.write( "Work hard to achieve success.\nKeep moving!!\n")
# 3.	file.close()

# The read() method

# 1.	file = open("test.txt", "r+") 
# 2.	str = file.read(10) 
# 3.	print ("Read String is : ", str)
# 4.	file.close()

# The rename() method

# 1.	Import os
# 2.	os.rename( "test1.txt", "test2.txt" )

# The remove() method

# 1.	import os
# 2.	os.remove("text2.txt")

# File flush() method 

# 1.	file = open("test.txt", "wb") 
# 2.	file.flush() 
# 3.	file.close()

# File fileno() method 

# 1.	file = open("test.txt", "wb") 
# 2.	fid = file.fileno() 
# 3.	print ("File Descriptor: ", fid) 
# 4.	file.close()

# File isatty() method  

# 1.	file = open("test.txt", "wb") 
# 2.	ret = file.isatty() 
# 3.	print ("Return value : ", ret)
# 4.	file.close()

# File next() method   

# 1.	file = open("test.txt", "r") 
# 2.	for index in range(5): 
# 3.	   line = next(file) 
# 4.	   print ("Line No %d - %s" % (index, line)) 
# 5.	file.close()

# File readline() method 

# 1.	file = open("test.txt", "r+") 
# 2.	line = file.readline() 
# 3.	print ("Read Line: %s" % (line)) 
# 4.	line = file.readline(3)

# File readlines() method 

# 1.	file = open("test.txt", "r+") 
# 2.	line = file.readlines() 
# 3.	print ("Read Line: %s" % (line)) 
# 4.	line = file.readlines(2) 
# 5.	print ("Read Line: %s" % (line)) 
# 6.	file.close()

# File seek() Method 

# 1.	file = open("test.txt", "rw+") 
# 2.	line = file.readlines() 
# 3.	print ("Read Line: %s" % (line))  
# 4.	file.seek(0, 0) 
# 5.	line = file.readline() 
# 6.	print ("Read Line: %s" % (line))  
# 7.	file.close()

# File tell() method

# 1.	file = open("test.txt", "r+") 
# 2.	line = file.readline() 
# 3.	print ("Read Line: %s" % (line)) 
# 4.	pos=file.tell() 
# 5.	print ("current position : ",pos)
# 6.	file.close()

# Program to write contents in a file
# a.	fo = open("file.txt", "w") 
# b.	fo.write( "A real man spends time with his family.\n")  
# c.	print("Data added to the file.") 
# d.	fo.close()

# Program to read the contents of a file
# a.	fo = open("file.txt", "w") 
# b.	fo.write( "A real man spends time with his family.\n")  
# c.	print("Data added to the file.") 
# d.	fo.close()

# Program to count the number of words in a text file



# 1.	fname=input("Enter file name: ")
# 2.	num_words=0
# 3.	with open(fname,"r") as f:
# 4.	    for line in f:
# 5.	        words=line.split()
# 6.	num_words+=len(words)
# 7.	print("Number of words: ")
# 8.	print(num_words)

# Program to count the number of lines in a text file
# a.	fname=input("Enter file name: ")
# b.	num_lines=0
# c.	with open(fname,"r") as f:
# d.	        for line in f:
# e.	num_lines+=1
# f.	print("Number of lines: ")
# g.	print(num_lines)

# Program to read a string from the user and append it into a file
# a.	fname=input("Enter a file: ")
# b.	file3=open(fname,"a")
# c.	c=input("Enter string to append: \n")
# d.	file3.write("\n")
# e.	file3.write(c)
# f.	file3.close()
# g.	print("Contents of append file: ")
# h.	file4=open(fname,"r")
# i.	line1=file4.readline()
# j.	while(line1!=""):
# k.	         print(line1)
# l.	         line1=file4.readline()

# Program to count the occurrences of a word in a text file

# 1.	fname=input("Enter file name: ")
# 2.	word=input("Enter word to be searched: ")
# 3.	k=0
# 4.	with open(fname,"r") as f:
# 5.	        for line in f:
# 6.	           words=line.split()
# 7.	           for i in words:
# 8.	                if(i==word):
# 9.	                    k=k+1
# 10.	print("Occurrences of the words: ")
# 11.	print(k)

# Program to copy the content of one file into another file
# a.	with open(“test.txt”) as f:
# b.	        with open(“out.txt”,”w”) as f1:
# c.	                for line in f:
# d.	                        f1.write(line)

# Program that reads a text file and counts the number of times a certain letter appears in the text file




# 1.	fname=input(“Enter file name: ”)
# 2.	            l=input(“Enter letter to be searched: ”)
# 3.	            k=0
# 4.	            with open(fname,’r’) as f:
# 5.	        for line in f:
# 6.	                 words=line.split()
# 7.	                  for i in words:
# 8.	                          for letter in i:
# 9.	                                  if(letter==l):
# 10.	                                           k=k+1
# 11.	print(“Occurrences of the letter: ”)
# 12.	print(k)

# Program to read a text file and print all the numbers present in the text file
# a.	fname=input(“Enter file name: ”)
# b.	with open(fname,’r’) as f:
# c.	        for line in f:
# d.	                 words=line.split()
# e.	                  for i in words:
# f.	                          for letter in i:
# g.	                                  if(letter.isdigit()):
# h.	                                          print(letter)
# i.	                                  k=1
# j.	if(k==0):
# k.	    print("No digit.")

# Program to append the contents of one file to another file

# 1.	name1=input(“Enter file to be read from: ”)
# 2.	name2=input(“Enter file to be appended to: ”)
# 3.	fin=open(name1,”r”)
# 4.	Data2=fin.read()
# 5.	fin.close()
# 6.	fout=open(name2,”a”)
# 7.	fout.write(data2)
# 8.	fout.close()

# 1.	fname=input("Enter file name: ")
# 2.	k=0
# 3.	with open(fname,"r") as f:
# 4.	    for line in f:
# 5.	        words=line.split()
# 6.	        for i in words:
# 7.	            for letter in i:
# 8.	                if(letter.isspace):
# 9.	                        k=k+1
# 10.	print("Occurrences of the letter: ")
# 11.	print(k)

