# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Af-cJgiZLVLmA_GWGL6xYZuG3tQuov1O
"""

# The import statement

# 1.	defprint_func( p ): 
# 2.	   print "Hello : ", p 
# 3.	   return

# import support 
# 2.	support.print_func("Sukhman")

# The from...import statement

# 1.	def fib(n):
# 2.	    r=[] 
# 3.	    a, b = 0, 1 
# 4.	    while (b<n): 
# 5.	r.append(b)  
# 6.	        a, b = b, a+b

# from Fibonacci import fib
# 2.	fib(50)
# 3.	[1, 1, 2, 3, 5, 8, 13, 21, 34]

# Executing Modules as Scripts

# 1.	If __name__==”__main__”:
# 2.	 Import sys
# 3.	 Fib(int(sys.argv[1]))

# The dir( ) function

# 1.	import math 
# 2.	con = dir(math) 
# 3.	print (con)

# reload() function

# 1.	reload(fibonacci)

# Packages in Python

# 1.	#!/user/bin/python3 
# 2.	def Pots(): 
# 3.	   print ("I'm Pots Phone")

# #!/usr/bin/python3 
# 2.	# Now import your Phone Package. 
# 3.	import Phone 
# 4.	Phone.Pots() 
# 5.	Phone.Isdn() 
# 6.	Phone.G3()

# Program to import the value of pi using math module

# 1.	import math
# 2.	print(“("The value of pi is ”, ", math.pi)

# Program to create a file called num.py containing square and cube of a number and import to print the same

# Num.py
# 1.	def square(x):
# 2.	                return x*x
# 3.	
# 4.	def cube(x):
# 5.	                return x*x*x

# Python interpreter
# 1.	import num
# 2.	num.square(3)
# 3.	            9
# 4.	num.cube(3)
# 5.	  27

# Program to print current time
# 4.	import time
# 5.	print(time.asctime())
# 6.	        ‘Wed Apr 9 02:54:21 2018’

# Program to print the current working directory
# 1.	import os
# 2.	print(os.getcwd.__doc__)

